Blog app - Add forms
TahenyBELGUITH/FacebookApp pull request #7
Opened 2022-10-29 10:47 UTC by TahenyBELGUITH

In this milestone I :  
- Create a method called current_user in the ApplicationController to make current user data available to all controllers. which returns the first user from the database.
- Create forms to perform the following functions:
     - Creates a Post.
     - Create a comment.
- Allow Users to add likes to Posts.

a code reviewer is appreciated  😄 
@TahenyBELGUITH

2022-10-29 11:20 UTC, KDlamini requested changes
### Hi @TahenyBELGUITH 🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Controllers set up correctly
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 11:20 UTC, KDlamini commented on config/routes.rb
>    end
[REQUIRED] Since `:posts` routes already exist inside `:user` routes, there's no need to create post routes again on line 6. This creates duplicated post routes and it's redundant.

You can move all the code on `line 6` to `line 3` so that you end up with:
```
  resources :users do
     resources :posts do
       resources :comments
       resources :likes
    end
  end
```

[OPTIONAL] Since you do not need all the routes for each controller for now:

- For `:users` you can include `only: [:index, :show]` which is coded like:
```
  resources :users, only: [:index, :show]` do
    ...
  end
```

- The same thing for `:comments`  should include `only: [:new, :create]` routes.
- and `:likes`  should include `only: [:create]` route.

2022-10-29 11:48 UTC, TahenyBELGUITH commented on config/routes.rb
>    end
@KDlamini  thank you for your review 😄 , I try your solution but it doesn't work! the user can't create post anymore neither  like it...

2022-10-29 14:41 UTC, TahenyBELGUITH commented on config/routes.rb
>    end
Hello @KDlamini, thank you for your review 😄 ,  I try to follow your approach  but it doesn't work as you can see in the video :
[screen record of your approach](https://user-images.githubusercontent.com/57154534/198837490-89643b67-7e21-4ca8-914a-d152684503fe.webm)

thank you for your consideration 😄

2022-10-29 15:19 UTC, elmar8287 approved these changes
Hi, @TahenyBELGUITH.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

### Highlights

- The app is working as fine and covers the milestone requerements 👍 

### Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 15:22 UTC, TahenyBELGUITH commented
Thank you for your review  @elmar8287 😄

2022-10-29 15:22 UTC, merged

2022-10-29 20:01 UTC, elmar8287 commented
> Thank you for your review @elmar8287 😄

🙂

2022-10-30 07:56 UTC, KDlamini commented on config/routes.rb
>    end
@TahenyBELGUITH That's because you have to update the routes on your forms. If you run `rails routes` you'll see that the paths have changed.